export interface Apartment {
  id: number;
  lat: number;
  lng: number;
  title: string;
  price: string;
  address: string;
  description: string;
  type: "apartment" | "house" | "studio";
  district: string;
  rooms?: number;
  area?: number;
  floor?: number;
   originalPrice?: string; // Цена до скидки
  photos?: string[]; // Массив URL фотографий
  amenities?: string[]; // Удобства
  hostName?: string; // Имя хозяина
  hostRating?: number; // Рейтинг хозяина
}


// Центры районов Нижнего Новгорода
const districtCenters = {
  Сормовский: { lat: 56.3287, lng: 43.8547 },
  Нижегородский: { lat: 56.2964, lng: 43.9361 },
  Советский: { lat: 56.29, lng: 43.99 },
  Приокский: { lat: 56.27, lng: 43.96 },
  Ленинский: { lat: 56.32, lng: 43.87 },
  Канавинский: { lat: 56.26, lng: 43.9 },
  Московский: { lat: 56.31, lng: 43.92 },
  Автозаводский: { lat: 56.25, lng: 43.86 },
};

// Функция для генерации случайных координат в районе
const generateCoordinates = (center: { lat: number; lng: number }) => {
  const randomOffset = () => (Math.random() - 0.5) * 0.03;
  return {
    lat: center.lat + randomOffset(),
    lng: center.lng + randomOffset(),
  };
};

// Генерация 100 жилищ: 40 квартир + 30 домов + 30 студий
export const apartments: Apartment[] = [
  // КВАРТИРЫ (40)
  // Сормовский район (5 квартир)
  {
    id: 1,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "1-комнатная у метро",
    price: "1800₽",
    address: "ул. Коминтерна, 15",
    description: "Уютная квартира в 5 минутах от метро",
    type: "apartment",
    district: "Сормовский",
    rooms: 1,
    area: 35,
    floor: 5,
  },
  {
    id: 2,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "2-комнатная",
    price: "2400₽",
    address: "ул. Ярошенко, 8",
    description: "Просторная для семьи или компании",
    type: "apartment",
    district: "Сормовский",
    rooms: 2,
    area: 48,
    floor: 7,
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор"],
  },
  {
    id: 3,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "3-комнатная",
    price: "3200₽",
    address: "ул. Свободы, 45",
    description: "Большая квартира в тихом дворе",
    type: "apartment",
    district: "Сормовский",
    rooms: 3,
    area: 65,
    floor: 4,
  },
  {
    id: 4,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "1-комнатная эконом",
    price: "1400₽",
    address: "ул. Зайцева, 10",
    description: "Бюджетный вариант у Сормовского парка",
    type: "apartment",
    district: "Сормовский",
    rooms: 1,
    area: 32,
    floor: 1,
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор"],
  },
  {
    id: 5,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "2-комнатная с балконом",
    price: "2600₽",
    address: "ул. Дмитрия Павлова, 20",
    description: "Свежий ремонт, есть вся техника",
    type: "apartment",
    district: "Сормовский",
    rooms: 2,
    area: 50,
    floor: 6,
  },

  // Нижегородский район (5 квартир)
  {
    id: 6,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "1-комнатная с видом на Кремль",
    price: "2800₽",
    address: "ул. Ильинская, 10",
    description: "Панорамный вид на исторический центр",
    type: "apartment",
    district: "Нижегородский",
    rooms: 1,
    area: 40,
    floor: 7,
    amenities: ["Wi-Fi", "Кондиционер", "Телевизор"],
  },
  {
    id: 7,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "2-комнатная у метро",
    price: "3200₽",
    address: "ул. Горького, 45",
    description: "Удобная транспортная развязка",
    type: "apartment",
    district: "Нижегородский",
    rooms: 2,
    area: 52,
    floor: 5,
  },
  {
    id: 8,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "3-комнатная в историческом доме",
    price: "3800₽",
    address: "ул. Пискунова, 12",
    description: "Старинный дом с высокими потолками",
    type: "apartment",
    district: "Нижегородский",
    rooms: 3,
    area: 70,
    floor: 3,
  },
  {
    id: 9,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "1-комнатная у набережной",
    price: "2600₽",
    address: "наб. Федоровского, 8",
    description: "Вид на Волгу, уютный дворик",
    type: "apartment",
    district: "Нижегородский",
    rooms: 1,
    area: 36,
    floor: 6,
  },
  {
    id: 10,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "2-комнатная с террасой",
    price: "3400₽",
    address: "ул. Сергиевская, 22",
    description: "Квартира с просторной террасой",
    type: "apartment",
    district: "Нижегородский",
    rooms: 2,
    area: 54,
    floor: 5,
  },

  // Советский район (5 квартир)
  {
    id: 11,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "1-комнатная в новостройке",
    price: "2500₽",
    address: "пр. Гагарина, 100",
    description: "Современный жилой комплекс",
    type: "apartment",
    district: "Советский",
    rooms: 1,
    area: 38,
    floor: 12,
  },
  {
    id: 12,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "2-комнатная у парка",
    price: "3000₽",
    address: "ул. Бекетова, 25",
    description: "Рядом с парком Дубки",
    type: "apartment",
    district: "Советский",
    rooms: 2,
    area: 50,
    floor: 6,
  },
  {
    id: 13,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "3-комнатная для семьи",
    price: "3800₽",
    address: "ул. Родионова, 80",
    description: "Просторная квартира с детской комнатой",
    type: "apartment",
    district: "Советский",
    rooms: 3,
    area: 68,
    floor: 8,
  },
  {
    id: 14,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "1-комнатная у университета",
    price: "2300₽",
    address: "ул. Тимирязева, 18",
    description: "Рядом с ННГУ",
    type: "apartment",
    district: "Советский",
    rooms: 1,
    area: 35,
    floor: 5,
  },
  {
    id: 15,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "2-комнатная с гардеробной",
    price: "3300₽",
    address: "ул. Ашхабадская, 24",
    description: "Просторная гардеробная комната",
    type: "apartment",
    district: "Советский",
    rooms: 2,
    area: 53,
    floor: 7,
  },

  // Приокский район (5 квартир)
  {
    id: 16,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "1-комнатная у метро",
    price: "1900₽",
    address: "ул. Маршала Воронова, 10",
    description: "Удобная транспортная доступность",
    type: "apartment",
    district: "Приокский",
    rooms: 1,
    area: 34,
    floor: 4,
  },
  {
    id: 17,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "2-комнатная у парка",
    price: "2700₽",
    address: "ул. Ларина, 20",
    description: "Рядом с Щелоковским хутором",
    type: "apartment",
    district: "Приокский",
    rooms: 2,
    area: 49,
    floor: 5,
  },
  {
    id: 18,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "3-комнатная",
    price: "3400₽",
    address: "ул. Терешковой, 25",
    description: "Просторная для большой компании",
    type: "apartment",
    district: "Приокский",
    rooms: 3,
    area: 67,
    floor: 7,
  },
  {
    id: 19,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "1-комнатная с балконом",
    price: "2000₽",
    address: "ул. Комсомольская, 30",
    description: "Просторный балкон с видом",
    type: "apartment",
    district: "Приокский",
    rooms: 1,
    area: 36,
    floor: 6,
  },
  {
    id: 20,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "2-комнатная для семьи",
    price: "2900₽",
    address: "ул. Академика Лебедева, 18",
    description: "Идеально для молодой семьи",
    type: "apartment",
    district: "Приокский",
    rooms: 2,
    area: 51,
    floor: 8,
  },

  // Ленинский район (5 квартир)
  {
    id: 21,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "1-комнатная у метро",
    price: "2100₽",
    address: "пр. Ленина, 50",
    description: "Центральное расположение",
    type: "apartment",
    district: "Ленинский",
    rooms: 1,
    area: 35,
    floor: 6,
  },
  {
    id: 22,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "2-комнатная с балконом",
    price: "2900₽",
    address: "ул. Бурнаковская, 30",
    description: "Свежий ремонт",
    type: "apartment",
    district: "Ленинский",
    rooms: 2,
    area: 52,
    floor: 7,
  },
  {
    id: 23,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "3-комнатная",
    price: "3600₽",
    address: "ул. Куйбышева, 40",
    description: "Для семьи с детьми",
    type: "apartment",
    district: "Ленинский",
    rooms: 3,
    area: 70,
    floor: 8,
  },
  {
    id: 24,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "1-комнатная у парка",
    price: "2300₽",
    address: "ул. Рябцева, 22",
    description: "Рядом с парком",
    type: "apartment",
    district: "Ленинский",
    rooms: 1,
    area: 38,
    floor: 5,
  },
  {
    id: 25,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "2-комнатная с видом",
    price: "3000₽",
    address: "ул. Чаадаева, 33",
    description: "Панорамный вид на город",
    type: "apartment",
    district: "Ленинский",
    rooms: 2,
    area: 54,
    floor: 9,
  },

  // Канавинский район (5 квартир)
  {
    id: 26,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "1-комнатная",
    price: "2200₽",
    address: "ул. Советская, 20",
    description: "Уютная квартира",
    type: "apartment",
    district: "Канавинский",
    rooms: 1,
    area: 36,
    floor: 5,
  },
  {
    id: 27,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "2-комнатная",
    price: "2800₽",
    address: "ул. Октябрьской революции, 25",
    description: "Просторная",
    type: "apartment",
    district: "Канавинский",
    rooms: 2,
    area: 50,
    floor: 7,
  },
  {
    id: 28,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "1-комнатная у метро",
    price: "2100₽",
    address: "ул. Интернациональная, 30",
    description: "Рядом со станцией метро",
    type: "apartment",
    district: "Канавинский",
    rooms: 1,
    area: 34,
    floor: 4,
  },
  {
    id: 29,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "3-комнатная",
    price: "3500₽",
    address: "ул. Маяковского, 42",
    description: "Для большой семьи",
    type: "apartment",
    district: "Канавинский",
    rooms: 3,
    area: 68,
    floor: 8,
  },
  {
    id: 30,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "2-комнатная у парка",
    price: "2900₽",
    address: "ул. Горького, 55",
    description: "Рядом с парком",
    type: "apartment",
    district: "Канавинский",
    rooms: 2,
    area: 53,
    floor: 6,
  },

  // Московский район (5 квартир)
  {
    id: 31,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "1-комнатная у метро",
    price: "2000₽",
    address: "ул. Березовская, 25",
    description: "Удобная транспортная доступность",
    type: "apartment",
    district: "Московский",
    rooms: 1,
    area: 35,
    floor: 6,
  },
  {
    id: 32,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "2-комнатная",
    price: "2700₽",
    address: "ул. Герцена, 30",
    description: "Просторная квартира",
    type: "apartment",
    district: "Московский",
    rooms: 2,
    area: 51,
    floor: 7,
  },
  {
    id: 33,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "3-комнатная для семьи",
    price: "3400₽",
    address: "ул. Бекетова, 45",
    description: "Идеально для семьи",
    type: "apartment",
    district: "Московский",
    rooms: 3,
    area: 69,
    floor: 8,
  },
  {
    id: 34,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "1-комнатная эконом",
    price: "1600₽",
    address: "ул. Гагарина, 22",
    description: "Бюджетный вариант",
    type: "apartment",
    district: "Московский",
    rooms: 1,
    area: 32,
    floor: 2,
  },
  {
    id: 35,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "2-комнатная с ремонтом",
    price: "2900₽",
    address: "ул. Ванеева, 35",
    description: "Современный ремонт",
    type: "apartment",
    district: "Московский",
    rooms: 2,
    area: 54,
    floor: 9,
  },

  // Автозаводский район (5 квартир)
  {
    id: 36,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "1-комнатная",
    price: "2000₽",
    address: "ул. Дьяконова, 15",
    description: "Современный район",
    type: "apartment",
    district: "Автозаводский",
    rooms: 1,
    area: 35,
    floor: 6,
  },
  {
    id: 37,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "2-комнатная",
    price: "2600₽",
    address: "ул. Краснодонцев, 20",
    description: "Для семьи",
    type: "apartment",
    district: "Автозаводский",
    rooms: 2,
    area: 52,
    floor: 7,
  },
  {
    id: 38,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "3-комнатная",
    price: "3200₽",
    address: "ул. Веденяпина, 25",
    description: "Просторная",
    type: "apartment",
    district: "Автозаводский",
    rooms: 3,
    area: 70,
    floor: 8,
  },
  {
    id: 39,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "1-комнатная",
    price: "2100₽",
    address: "ул. Школьная, 40",
    description: "Рядом со школами",
    type: "apartment",
    district: "Автозаводский",
    rooms: 1,
    area: 37,
    floor: 5,
  },
  {
    id: 40,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "2-комнатная с балконом",
    price: "2700₽",
    address: "ул. Дьяконова, 30",
    description: "Просторный балкон",
    type: "apartment",
    district: "Автозаводский",
    rooms: 2,
    area: 53,
    floor: 7,
  },

  // ДОМА (30)
  // Сормовский район (4 дома)
  {
    id: 41,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Частный дом с садом",
    price: "4500₽",
    address: "ул. Мончегорская, 7",
    description: "Уютный дом с большим участком",
    type: "house",
    district: "Сормовский",
    rooms: 3,
    area: 85,
    photos: [
      "/apartments/41/main.jpg", // ГЛАВНАЯ фотография для превью
    ],
    amenities: ["Баня/Сауна", "Мангал/Гриль", "Гараж"],
  },
  {
    id: 42,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Дом с бассейном",
    price: "6800₽",
    address: "ул. Коминтерна, 25",
    description: "Роскошный дом с частным бассейном",
    type: "house",
    district: "Сормовский",
    rooms: 4,
    area: 120,
    photos: [
      "/apartments/42/main.jpg", // ГЛАВНАЯ фотография для превью
    ],
    amenities: ["Баня/Сауна", "Мангал/Гриль", "Гараж"],
  },
  {
    id: 43,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Коттедж у парка",
    price: "5200₽",
    address: "ул. Зайцева, 15",
    description: "Современный коттедж рядом с парком",
    type: "house",
    district: "Сормовский",
    rooms: 3,
    area: 95,
    photos: [
      "/apartments/43/main.jpg", // ГЛАВНАЯ фотография для превью
    ],
  },
  {
    id: 44,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Дом для большой семьи",
    price: "5800₽",
    address: "ул. Ярошенко, 12",
    description: "Просторный дом с детской площадкой",
    type: "house",
    district: "Сормовский",
    rooms: 5,
    area: 140,
    photos: [
      "/apartments/44/main.jpg", // ГЛАВНАЯ фотография для превью
    ],
  },

  // Нижегородский район (4 дома)
  {
    id: 45,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Таунхаус в центре",
    price: "6200₽",
    address: "ул. Рождественская, 8",
    description: "Современный таунхаус в историческом центре",
    type: "house",
    district: "Нижегородский",
    rooms: 3,
    area: 110,
  },
  {
    id: 46,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Дом с камином",
    price: "5500₽",
    address: "ул. Ильинская, 5",
    description: "Уютный дом с камином и садом",
    type: "house",
    district: "Нижегородский",
    rooms: 4,
    area: 130,
    amenities: ["Баня/Сауна", "Мангал/Гриль", "Гараж"],
  },
  {
    id: 47,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Особняк премиум",
    price: "8500₽",
    address: "ул. Большая Покровская, 3",
    description: "Элитный особняк с охраняемой территорией",
    type: "house",
    district: "Нижегородский",
    rooms: 6,
    area: 200,
  },
  {
    id: 48,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Дом у набережной",
    price: "7200₽",
    address: "наб. Федоровского, 2",
    description: "Дом с видом на Волгу",
    type: "house",
    district: "Нижегородский",
    rooms: 4,
    area: 150,
  },

  // Советский район (4 дома)
  {
    id: 49,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Коттедж в лесной зоне",
    price: "4800₽",
    address: "ул. Ларина, 8",
    description: "Уединенный коттедж в лесопарковой зоне",
    type: "house",
    district: "Советский",
    rooms: 3,
    area: 100,
  },
  {
    id: 50,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Дом с сауной",
    price: "5900₽",
    address: "ул. Бекетова, 10",
    description: "Дом с собственной сауной и баней",
    type: "house",
    district: "Советский",
    rooms: 4,
    area: 125,
  },
  {
    id: 51,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Семейный дом",
    price: "5100₽",
    address: "ул. Родионова, 15",
    description: "Идеальный дом для семейного отдыха",
    type: "house",
    district: "Советский",
    rooms: 4,
    area: 115,
  },
  {
    id: 52,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Дом у университета",
    price: "4600₽",
    address: "ул. Тимирязева, 7",
    description: "Удобное расположение рядом с ННГУ",
    type: "house",
    district: "Советский",
    rooms: 3,
    area: 90,
  },

  // Приокский район (4 дома)
  {
    id: 53,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Частный дом",
    price: "5000₽",
    address: "ул. Архангельская, 5",
    description: "Уютный дом в тихом районе",
    type: "house",
    district: "Приокский",
    rooms: 3,
    area: 90,
  },
  {
    id: 54,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Дом с гаражом",
    price: "5400₽",
    address: "ул. Маршала Воронова, 3",
    description: "Дом с просторным гаражом на 2 машины",
    type: "house",
    district: "Приокский",
    rooms: 3,
    area: 105,
  },
  {
    id: 55,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Коттедж у ботанического сада",
    price: "5700₽",
    address: "ул. Юбилейная, 8",
    description: "Коттедж рядом с ботаническим садом",
    type: "house",
    district: "Приокский",
    rooms: 4,
    area: 120,
  },
  {
    id: 56,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Дом с террасой",
    price: "4900₽",
    address: "ул. Лесная, 12",
    description: "Дом с просторной террасой для отдыха",
    type: "house",
    district: "Приокский",
    rooms: 3,
    area: 95,
  },

  // Ленинский район (4 дома)
  {
    id: 57,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Частный дом у реки",
    price: "4800₽",
    address: "ул. Набережная, 7",
    description: "Дом с видом на реку",
    type: "house",
    district: "Ленинский",
    rooms: 3,
    area: 95,
  },
  {
    id: 58,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Дом в спальном районе",
    price: "4200₽",
    address: "ул. Республиканская, 8",
    description: "Уютный дом в спокойном районе",
    type: "house",
    district: "Ленинский",
    rooms: 3,
    area: 85,
  },
  {
    id: 59,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Коттедж с бассейном",
    price: "7500₽",
    address: "ул. Ванеева, 5",
    description: "Элитный коттедж с частным бассейном",
    type: "house",
    district: "Ленинский",
    rooms: 5,
    area: 160,
  },
  {
    id: 60,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Дом для отдыха",
    price: "5200₽",
    address: "ул. Рябцева, 10",
    description: "Идеальный дом для weekend-отдыха",
    type: "house",
    district: "Ленинский",
    rooms: 4,
    area: 110,
  },

  // Канавинский район (3 дома)
  {
    id: 61,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "Дом в центре",
    price: "5300₽",
    address: "ул. Самочкина, 10",
    description: "Дом в историческом центре",
    type: "house",
    district: "Канавинский",
    rooms: 3,
    area: 100,
  },
  {
    id: 62,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "Таунхаус у вокзала",
    price: "4600₽",
    address: "ул. Чкалова, 8",
    description: "Современный таунхаус рядом с вокзалом",
    type: "house",
    district: "Канавинский",
    rooms: 3,
    area: 95,
  },
  {
    id: 63,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "Дом с садом",
    price: "5800₽",
    address: "ул. Советская, 15",
    description: "Дом с ухоженным садом и беседкой",
    type: "house",
    district: "Канавинский",
    rooms: 4,
    area: 125,
  },

  // Московский район (3 дома)
  {
    id: 64,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "Частный дом",
    price: "4700₽",
    address: "ул. Лесная, 12",
    description: "Уютный частный дом",
    type: "house",
    district: "Московский",
    rooms: 3,
    area: 105,
  },
  {
    id: 65,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "Дом у метро",
    price: "5100₽",
    address: "ул. Березовская, 5",
    description: "Удобное расположение рядом с метро",
    type: "house",
    district: "Московский",
    rooms: 3,
    area: 115,
  },
  {
    id: 66,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "Коттедж для семьи",
    price: "5600₽",
    address: "ул. Герцена, 8",
    description: "Просторный коттедж для большой семьи",
    type: "house",
    district: "Московский",
    rooms: 4,
    area: 135,
  },

  // Автозаводский район (4 дома)
  {
    id: 67,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Дом с садом",
    price: "5100₽",
    address: "ул. Садовая, 8",
    description: "Дом с садом",
    type: "house",
    district: "Автозаводский",
    rooms: 4,
    area: 115,
  },
  {
    id: 68,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Коттедж в новом районе",
    price: "4900₽",
    address: "ул. Дьяконова, 12",
    description: "Современный коттедж в развивающемся районе",
    type: "house",
    district: "Автозаводский",
    rooms: 3,
    area: 105,
  },
  {
    id: 69,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Дом для мероприятий",
    price: "6800₽",
    address: "ул. Краснодонцев, 15",
    description: "Просторный дом для проведения мероприятий",
    type: "house",
    district: "Автозаводский",
    rooms: 5,
    area: 180,
  },
  {
    id: 70,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Таунхаус эконом",
    price: "3800₽",
    address: "ул. Школьная, 5",
    description: "Бюджетный таунхаус для молодой семьи",
    type: "house",
    district: "Автозаводский",
    rooms: 2,
    area: 80,
  },

  // СТУДИИ (30)
  // Сормовский район (4 студии)
  {
    id: 71,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Студия с ремонтом",
    price: "1600₽",
    address: "пр. Кораблестроителей, 25",
    description: "Современный ремонт, вся техника",
    type: "studio",
    district: "Сормовский",
    area: 28,
    floor: 3,
  },
  {
    id: 72,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Студия у парка",
    price: "1550₽",
    address: "ул. Буревестника, 22",
    description: "Тихая студия рядом с парком",
    type: "studio",
    district: "Сормовский",
    area: 26,
    floor: 3,
  },
  {
    id: 73,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Студия для студентов",
    price: "1450₽",
    address: "ул. Коминтерна, 18",
    description: "Идеальный вариант для студентов",
    type: "studio",
    district: "Сормовский",
    area: 25,
    floor: 2,
  },
  {
    id: 74,
    ...generateCoordinates(districtCenters["Сормовский"]),
    title: "Студия с балконом",
    price: "1700₽",
    address: "ул. Энгельса, 20",
    description: "Студия с уютным балконом",
    type: "studio",
    district: "Сормовский",
    area: 30,
    floor: 5,
  },

  // Нижегородский район (4 студии)
  {
    id: 75,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Студия в центре",
    price: "2200₽",
    address: "ул. Рождественская, 25",
    description: "В самом сердце города",
    type: "studio",
    district: "Нижегородский",
    area: 30,
    floor: 4,
  },
  {
    id: 76,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Студия для студентов",
    price: "1800₽",
    address: "ул. Минина, 20",
    description: "Рядом с университетами",
    type: "studio",
    district: "Нижегородский",
    area: 25,
    floor: 2,
  },
  {
    id: 77,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Студия с камином",
    price: "2400₽",
    address: "ул. Алексеевская, 18",
    description: "Уникальная студия с камином",
    type: "studio",
    district: "Нижегородский",
    area: 32,
    floor: 4,
  },
  {
    id: 78,
    ...generateCoordinates(districtCenters["Нижегородский"]),
    title: "Студия у театра",
    price: "2100₽",
    address: "ул. Варварская, 15",
    description: "Рядом с театром драмы",
    type: "studio",
    district: "Нижегородский",
    area: 28,
    floor: 3,
  },

  // Советский район (4 студии)
  {
    id: 79,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Студия с мебелью",
    price: "2000₽",
    address: "ул. Васнецова, 15",
    description: "Полностью меблированная",
    type: "studio",
    district: "Советский",
    area: 27,
    floor: 4,
  },
  {
    id: 80,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Студия с панорамными окнами",
    price: "2200₽",
    address: "пр. Ленина, 88",
    description: "Светлая студия с видом на город",
    type: "studio",
    district: "Советский",
    area: 29,
    floor: 9,
  },
  {
    id: 81,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Студия для молодоженов",
    price: "2100₽",
    address: "ул. Бекетова, 33",
    description: "Романтичная студия для пары",
    type: "studio",
    district: "Советский",
    area: 26,
    floor: 3,
  },
  {
    id: 82,
    ...generateCoordinates(districtCenters["Советский"]),
    title: "Студия эконом",
    price: "1700₽",
    address: "ул. Тимирязева, 22",
    description: "Бюджетный вариант для студентов",
    type: "studio",
    district: "Советский",
    area: 24,
    floor: 1,
  },

  // Приокский район (4 студии)
  {
    id: 83,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Студия с ремонтом",
    price: "1700₽",
    address: "ул. академика Сахарова, 15",
    description: "Современный дизайн",
    type: "studio",
    district: "Приокский",
    area: 26,
    floor: 2,
  },
  {
    id: 84,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Студия у ботанического сада",
    price: "1850₽",
    address: "ул. Юбилейная, 12",
    description: "Рядом с ботаническим садом",
    type: "studio",
    district: "Приокский",
    area: 28,
    floor: 3,
  },
  {
    id: 85,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Студия с гардеробной",
    price: "1950₽",
    address: "ул. Бурнаковская, 25",
    description: "Просторная гардеробная",
    type: "studio",
    district: "Приокский",
    area: 31,
    floor: 4,
  },
  {
    id: 86,
    ...generateCoordinates(districtCenters["Приокский"]),
    title: "Студия для работы",
    price: "1800₽",
    address: "ул. Маршала Воронова, 18",
    description: "Идеально для удаленной работы",
    type: "studio",
    district: "Приокский",
    area: 27,
    floor: 5,
  },

  // Ленинский район (4 студии)
  {
    id: 87,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Студия эконом",
    price: "1500₽",
    address: "ул. Республиканская, 15",
    description: "Бюджетный вариант",
    type: "studio",
    district: "Ленинский",
    area: 24,
    floor: 1,
  },
  {
    id: 88,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Студия для студентов",
    price: "1700₽",
    address: "ул. Дьяконова, 18",
    description: "Рядом с университетом",
    type: "studio",
    district: "Ленинский",
    area: 27,
    floor: 3,
  },
  {
    id: 89,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Студия с техникой",
    price: "1900₽",
    address: "ул. Бекетова, 28",
    description: "Вся необходимая техника",
    type: "studio",
    district: "Ленинский",
    area: 29,
    floor: 4,
  },
  {
    id: 90,
    ...generateCoordinates(districtCenters["Ленинский"]),
    title: "Студия у метро",
    price: "2100₽",
    address: "ул. Ванеева, 22",
    description: "Удобная транспортная доступность",
    type: "studio",
    district: "Ленинский",
    area: 30,
    floor: 6,
  },

  // Канавинский район (3 студии)
  {
    id: 91,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "Студия у вокзала",
    price: "1900₽",
    address: "ул. Чкалова, 15",
    description: "Удобно для командировочных",
    type: "studio",
    district: "Канавинский",
    area: 25,
    floor: 2,
  },
  {
    id: 92,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "Студия для молодых",
    price: "1750₽",
    address: "ул. Интернациональная, 22",
    description: "Идеально для молодежи",
    type: "studio",
    district: "Канавинский",
    area: 27,
    floor: 2,
  },
  {
    id: 93,
    ...generateCoordinates(districtCenters["Канавинский"]),
    title: "Студия с балконом",
    price: "1950₽",
    address: "ул. Канавинская, 16",
    description: "Просторный балкон",
    type: "studio",
    district: "Канавинский",
    area: 28,
    floor: 4,
  },

  // Московский район (3 студии)
  {
    id: 94,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "Студия с мебелью",
    price: "1700₽",
    address: "ул. Чаадаева, 18",
    description: "Полностью меблированная",
    type: "studio",
    district: "Московский",
    area: 26,
    floor: 3,
  },
  {
    id: 95,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "Студия у парка",
    price: "1850₽",
    address: "ул. Тимирязева, 28",
    description: "Рядом с парком",
    type: "studio",
    district: "Московский",
    area: 27,
    floor: 4,
  },
  {
    id: 96,
    ...generateCoordinates(districtCenters["Московский"]),
    title: "Студия для студентов",
    price: "1750₽",
    address: "ул. Ульянова, 20",
    description: "Рядом с университетом",
    type: "studio",
    district: "Московский",
    area: 25,
    floor: 2,
  },

  // Автозаводский район (4 студии)
  {
    id: 97,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Студия",
    price: "1600₽",
    address: "пр. Молодежный, 10",
    description: "Молодежный район",
    type: "studio",
    district: "Автозаводский",
    area: 25,
    floor: 3,
  },
  {
    id: 98,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Студия",
    price: "1800₽",
    address: "ул. Магистральная, 35",
    description: "Удобное расположение",
    type: "studio",
    district: "Автозаводский",
    area: 27,
    floor: 4,
    amenities: ["Wi-Fi", "Кухня", "Лифт", "Балкон"],
  },
  {
    id: 99,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Студия для студентов",
    price: "1700₽",
    address: "ул. Комсомольская, 25",
    description: "Рядом с учебными заведениями",
    type: "studio",
    district: "Автозаводский",
    area: 26,
    floor: 2,
    amenities: ["Wi-Fi", "Кухня", "Лифт", "Балкон"],
  },
  {
    id: 100,
    ...generateCoordinates(districtCenters["Автозаводский"]),
    title: "Студия с видом",
    price: "1900₽",
    address: "ул. Дьяконова, 25",
    description: "Светлая студия с панорамными окнами",
    type: "studio",
    district: "Автозаводский",
    area: 29,
    floor: 7,
    amenities: ["Wi-Fi", "Кухня", "Лифт", "Балкон"],
  },
];
